package CarInsuranceCompany;

import java.util.Random;

public class PolicyException extends Exception {

    private int ID;

    public PolicyException(int ID) throws PolicyException{

        this.ID = ID;
    }

    public String toString(){
        return "The Policy ID was not valid and a new ID (the generated ID) is generated by admin and assigned for the Policy";
    }

}
